### ISSUE TITLE
Organize the folder structure of the project

### ISSUE THREAD

**Issue by jahid114** [jahid114/ecommerce-app#3]
Inside every package of the src directory, make the following folders model, service, request, and response. Then move all the entity classes into the model folder, all the service & repository classes into the service folder, request-related classes into the request folder & response-related classes into the response folder. Also, rename the DTOs used as the request & response class.

**Comment by Noxiium** [comment]
I can help you with this. 
Where do you want the Controller classes, in the request folder?

**Comment by jahid114** [comment]
Okay , I am assigning this task to you. Controller classes should be in a separate controller folder.
